const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
const ON_SWITCH_ACCOUNT = 'ON_SWITCH_ACCOUNT'
const ON_IMPORT_ACCOUNT = 'ON_IMPORT_ACCOUNT'
export {
	GET_ACCOUNT_INFO,
	ON_SWITCH_ACCOUNT,
	ON_IMPORT_ACCOUNT,
	
}