const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
const ON_SWITCH_ACCOUNT = 'ON_SWITCH_ACCOUNT'
const ON_IMPORT_ACCOUNT = 'ON_IMPORT_ACCOUNT'
const ON_DELETE_ACCOUNT = 'ON_DELETE_ACCOUNT'
const RESET_DELETE_STATUS = 'RESET_DELETE_STATUS'
const UPDATE_BACKUP_STATUS = 'UPDATE_BACKUP_STATUS'
export {
	GET_ACCOUNT_INFO,
	ON_SWITCH_ACCOUNT,
	ON_IMPORT_ACCOUNT,
	ON_DELETE_ACCOUNT,
	RESET_DELETE_STATUS,
	UPDATE_BACKUP_STATUS,	
}