const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
const ON_SWITCH_ACCOUNT = 'ON_SWITCH_ACCOUNT'
const ON_IMPORT_ACCOUNT = 'ON_IMPORT_ACCOUNT'
// const IMPORT_ACCOUNT_SUCC = 'IMPORT_ACCOUNT_SUCC'
// const IMPORT_ACCOUNT_FAIL = 'IMPORT_ACCOUNT_FAIL'
// const ON_DELETE_ACCOUNT = 'ON_DELETE_ACCOUNT'
const RESET_DELETE_STATUS = 'RESET_DELETE_STATUS'
const UPDATE_BACKUP_STATUS = 'UPDATE_BACKUP_STATUS'
const ON_DELETE_ACCOUNT_START = 'ON_DELETE_ACCOUNT_START'
const ON_DELETE_ACCOUNT_SUC = 'ON_DELETE_ACCOUNT_SUC'
const ON_DELETE_ACCOUNT_FAIL = 'ON_DELETE_ACCOUNT_FAIL'

const PASS_ACCOUNTS_INFO_START = 'PASS_ACCOUNTS_INFO_START'
const PASS_ACCOUNTS_INFO_SUC = 'PASS_ACCOUNTS_INFO_SUC'
const PASS_ACCOUNTS_INFO_FAIL = 'PASS_ACCOUNTS_INFO_FAIL'

const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START'
const CREATE_ACCOUNT_SUC = 'CREATE_ACCOUNT_SUC'
const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL'


const IMPORT_ACCOUNT_START = 'IMPORT_ACCOUNT_START'
const IMPORT_ACCOUNT_SUC = 'IMPORT_ACCOUNT_SUC'
const IMPORT_ACCOUNT_FAIL = 'IMPORT_ACCOUNT_FAIL'

export {
	GET_ACCOUNT_INFO,
	ON_SWITCH_ACCOUNT,
	ON_IMPORT_ACCOUNT,
	// ON_DELETE_ACCOUNT,
	RESET_DELETE_STATUS,
	UPDATE_BACKUP_STATUS,	
	// IMPORT_ACCOUNT_SUCC,
	// IMPORT_ACCOUNT_FAIL,

	ON_DELETE_ACCOUNT_START,
	ON_DELETE_ACCOUNT_SUC,
	ON_DELETE_ACCOUNT_FAIL,

	PASS_ACCOUNTS_INFO_START,
	PASS_ACCOUNTS_INFO_SUC,
	PASS_ACCOUNTS_INFO_FAIL,

	CREATE_ACCOUNT_START,
	CREATE_ACCOUNT_SUC,
	CREATE_ACCOUNT_FAIL,

	IMPORT_ACCOUNT_START,
	IMPORT_ACCOUNT_SUC,
	IMPORT_ACCOUNT_FAIL,
}