const INSERT_TO_TOKEN_DB = 'INSERT_TO_TOKEN_DB'
const GET_ASSETS_LIST = 'GET_ASSETS_LIST'
const SELECTED_TOKEN_LIST = 'SELECTED_TOKEN_LIST'
const DELETE_TOKEN_LIST = 'DELETE_TOKEN_LIST'
const ADD_TOKEN_LIST = 'ADD_TOKEN_LIST'
const INIT_SELECTED_LIST = 'INIT_SELECTED_LIST'
const REFRESH_TOKEN_INFO = 'REFRESH_TOKEN_INFO'
const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export {
	INSERT_TO_TOKEN_DB,
	GET_ASSETS_LIST,
	SELECTED_TOKEN_LIST,
	DELETE_TOKEN_LIST,
	ADD_TOKEN_LIST,
	INIT_SELECTED_LIST,
	REFRESH_TOKEN_INFO,
	REFRESH_TOKEN_SUCCESS
}