const SAVE_TO_RECORD_START = 'SAVE_TO_RECORD_START'
const SAVE_TO_RECORD_SUC = 'SAVE_TO_RECORD_SUC'
const SAVE_TO_RECORD_FAIL = 'SAVE_TO_RECORD_FAIL'
export {
	SAVE_TO_RECORD_START,
	SAVE_TO_RECORD_SUC,
	SAVE_TO_RECORD_FAIL,
}